apiVersion: apps/v1
kind: Deployment
metadata:
  name: fouaneregistry
spec:
    replicas: 1
    selector:
      matchLabels:
        app: fouaneregistry
    template:
      metadata:
        labels:
          app: fouaneregistry
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: fouaneregistry
            image: fouaneregistry.azurecr.io/fouaneregistry:latest
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: '0'
                memory: '0'
              limits:
                cpu: '256'
                memory: 11400G
