apiVersion: apps/v1
kind: Deployment
metadata:
  name: setapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: setapp
  template:
    metadata:
      labels:
        app: setapp
    spec:
      containers:
      - name: setapp
        image: fouaneregistry.azurecr.io/fouaneregistry/fouaneregistry:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
