 - apiVersion: v1
  kind: Namespace
  metadata:
    name: default-1704324419296
  spec:
    finalizers:
      - kubernetes
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: fouaneregistry
    namespace: default-1704324419296
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: fouaneregistry
    template:
      metadata:
        labels:
          app: fouaneregistry
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: fouaneregistry
            image: fouaneregistry.azurecr.io/fouaneregistry:latest
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: '0'
                memory: '0'
              limits:
                cpu: '256'
                memory: 11400G
- apiVersion: v1
  kind: Service
  metadata:
    name: fouaneregistry-service
    namespace: default-1704324419296
  spec:
    type: LoadBalancer
    ports:
      - targetPort: 80
        name: port80
        port: 80
        protocol: TCP
    selector:
      app: fouaneregistry
