apiVersion: v1
kind: Service
metadata:
  name: fouaneregistry-service  
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      name: port80
      port: 80
      protocol: TCP
  selector:
    app: fouaneregistry
